language: cpp

# BEGIN BUILD MATRIX
#
# Build matrix must be smaller on branch coverity_scan because quota allows
# only 5 Coverity Scan jobs at once. Thus we have different versions of this
# file on branch master and coverity_scan.
#
# Please keep this file as much in sync as possible to allow easy merging
# from master into coverity_scan and only have differences in the build
# matrix block.
#
# Check the difference as follows:
#   $ git checkout master
#   $ git checkout coverity_scan
#   $ git difftool master coverity_scan .travis.yml
os:
  - linux
  - osx

osx_image: xcode7

compiler:
  - clang
  - gcc

env:
  matrix:
    - TARGETOS="native" MODULES="all" BOOST="n" BUILD_MODE="shared"
    - TARGETOS="native" MODULES="all" BOOST="n" BUILD_MODE="static"
    - TARGETOS="native" MODULES="all" BOOST="n" BUILD_MODE="coverage"
    - TARGETOS="native" MODULES="all" BOOST="n" BUILD_MODE="sanitizer"
    - TARGETOS="native" MODULES="all" BOOST="y" BUILD_MODE="shared"
    - TARGETOS="native" MODULES="all" BOOST="y" BUILD_MODE="static"
    - TARGETOS="native" MODULES="all" BOOST="y" BUILD_MODE="coverage"
    - TARGETOS="native" MODULES="all" BOOST="y" BUILD_MODE="sanitizer"

    - TARGETOS="native" MODULES="min" BOOST="n" BUILD_MODE="shared"
    - TARGETOS="native" MODULES="min" BOOST="n" BUILD_MODE="static"
    - TARGETOS="native" MODULES="min" BOOST="y" BUILD_MODE="shared"
    - TARGETOS="native" MODULES="min" BOOST="y" BUILD_MODE="static"

    - TARGETOS="ios32" MODULES="all" BOOST="n" BUILD_MODE="static"
    - TARGETOS="ios64" MODULES="all" BOOST="n" BUILD_MODE="static"

matrix:
  exclude:
    - os: osx
      compiler: gcc

    # No boost on Linux because installing Boost is easier on OS X
    - os: linux
      env: TARGETOS="native" MODULES="all" BOOST="y" BUILD_MODE="shared"
    - os: linux
      env: TARGETOS="native" MODULES="all" BOOST="y" BUILD_MODE="static"
    - os: linux
      env: TARGETOS="native" MODULES="all" BOOST="y" BUILD_MODE="coverage"
    - os: linux
      env: TARGETOS="native" MODULES="all" BOOST="y" BUILD_MODE="sanitizer"
    - os: linux
      env: TARGETOS="native" MODULES="min" BOOST="y" BUILD_MODE="shared"
    - os: linux
      env: TARGETOS="native" MODULES="min" BOOST="y" BUILD_MODE="static"

    # No coverage and sanitizer on clang
    - compiler: clang
      env: TARGETOS="native" MODULES="all" BOOST="n" BUILD_MODE="coverage"
    - compiler: clang
      env: TARGETOS="native" MODULES="all" BOOST="n" BUILD_MODE="sanitizer"
    - compiler: clang
      env: TARGETOS="native" MODULES="all" BOOST="y" BUILD_MODE="coverage"
    - compiler: clang
      env: TARGETOS="native" MODULES="all" BOOST="y" BUILD_MODE="sanitizer"

    # No minimal builds on clang
    - compiler: clang
      env: TARGETOS="native" MODULES="min" BOOST="n" BUILD_MODE="shared"
    - compiler: clang
      env: TARGETOS="native" MODULES="min" BOOST="n" BUILD_MODE="static"
    - compiler: clang
      env: TARGETOS="native" MODULES="min" BOOST="y" BUILD_MODE="shared"
    - compiler: clang
      env: TARGETOS="native" MODULES="min" BOOST="y" BUILD_MODE="static"

    - os: linux
      env: TARGETOS="ios32" MODULES="all" BOOST="n" BUILD_MODE="static"
    - os: linux
      env: TARGETOS="ios64" MODULES="all" BOOST="n" BUILD_MODE="static"
# END BUILD MATRIX

cache:
  directories:
    - $HOME/.ccache

install:
  - ./src/scripts/ci/travis/install.sh

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./src/scripts/ci/travis/build.sh ; fi

after_success:
  - ./src/scripts/ci/travis/after_success.sh

notifications:
  email: botan-commits@lists.randombit.net

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - ccache
    - g++-4.8
    - libssl-dev
    - libsqlite3-dev
    - zlib1g-dev
    - libbz2-dev
    - liblzma-dev
    - python2
    - python3

  coverity_scan:
    project:
      name: "randombit/botan"
    notification_email: lloyd@randombit.net
    build_command_prepend: "./configure.py --cc-bin=/usr/bin/g++-4.8"
    build_command: "make -j2"
    branch_pattern: coverity_scan
